# Generated by Django 4.2.1 on 2023-06-13 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
